export const dashboard_data = {
  data: [
    {
      companyName: "Nova",
      description: "Fintech Solution",
      details: "Leading innovation",
      lastChecked: "July 19, 2026",
      performance: 73,
      status: "Pending",
      website: "nova.com",
    },
    {
      companyName: "Pioneer",
      description: "E-commerce Platform",
      details: "Revolutionizing the market",
      lastChecked: "July 15, 2026",
      performance: 32,
      status: "Paid",
      website: "pioneer.com",
    },
    {
      companyName: "Cosmos",
      description: "Cloud Service",
      details: "Cutting-edge technology",
      lastChecked: "July 6, 2026",
      performance: 20,
      status: "Pending",
      website: "cosmos.com",
    },
    {
      companyName: "Helix",
      description: "AI-powered Tool",
      details: "Next-gen solutions",
      lastChecked: "July 21, 2026",
      performance: 2,
      status: "Failed",
      website: "helix.com",
    },
    {
      companyName: "Zenith",
      description: "Blockchain App",
      details: "Advanced services",
      lastChecked: "July 15, 2026",
      performance: 62,
      status: "Paid",
      website: "zenith.com",
    },
    {
      companyName: "Quantum",
      description: "Healthcare Tech",
      details: "Premium experience",
      lastChecked: "July 1, 2026",
      performance: 28,
      status: "Pending",
      website: "quantum.com",
    },
    {
      companyName: "Apex",
      description: "EdTech Solution",
      details: "Top-notch performance",
      lastChecked: "July 28, 2026",
      performance: 60,
      status: "Pending",
      website: "apex.com",
    },
    {
      companyName: "Synergy",
      description: "Logistics App",
      details: "Unmatched quality",
      lastChecked: "July 5, 2026",
      performance: 5,
      status: "Pending",
      website: "synergy.com",
    },
    {
      companyName: "Vertex",
      description: "Gaming Platform",
      details: "Seamless integration",
      lastChecked: "July 3, 2026",
      performance: 78,
      status: "Paid",
      website: "vertex.com",
    },
    {
      companyName: "Omni",
      description: "Streaming Service",
      details: "Outstanding support",
      lastChecked: "July 20, 2026",
      performance: 59,
      status: "Failed",
      website: "omni.com",
    },
    {
      companyName: "Nova",
      description: "Fintech Solution",
      details: "Leading innovation",
      lastChecked: "July 21, 2026",
      performance: 60,
      status: "Failed",
      website: "nova.com",
    },
    {
      companyName: "Pioneer",
      description: "E-commerce Platform",
      details: "Revolutionizing the market",
      lastChecked: "July 1, 2026",
      performance: 39,
      status: "Paid",
      website: "pioneer.com",
    },
    {
      companyName: "Cosmos",
      description: "Cloud Service",
      details: "Cutting-edge technology",
      lastChecked: "July 2, 2026",
      performance: 95,
      status: "Pending",
      website: "cosmos.com",
    },
    {
      companyName: "Helix",
      description: "AI-powered Tool",
      details: "Next-gen solutions",
      lastChecked: "July 5, 2026",
      performance: 39,
      status: "Paid",
      website: "helix.com",
    },
    {
      companyName: "Zenith",
      description: "Blockchain App",
      details: "Advanced services",
      lastChecked: "July 13, 2026",
      performance: 31,
      status: "Pending",
      website: "zenith.com",
    },
    {
      companyName: "Quantum",
      description: "Healthcare Tech",
      details: "Premium experience",
      lastChecked: "July 28, 2026",
      performance: 22,
      status: "Paid",
      website: "quantum.com",
    },
    {
      companyName: "Apex",
      description: "EdTech Solution",
      details: "Top-notch performance",
      lastChecked: "July 24, 2026",
      performance: 16,
      status: "Pending",
      website: "apex.com",
    },
    {
      companyName: "Synergy",
      description: "Logistics App",
      details: "Unmatched quality",
      lastChecked: "July 18, 2026",
      performance: 76,
      status: "Paid",
      website: "synergy.com",
    },
    {
      companyName: "Vertex",
      description: "Gaming Platform",
      details: "Seamless integration",
      lastChecked: "July 27, 2026",
      performance: 50,
      status: "Pending",
      website: "vertex.com",
    },
    {
      companyName: "Omni",
      description: "Streaming Service",
      details: "Outstanding support",
      lastChecked: "July 15, 2026",
      performance: 66,
      status: "Paid",
      website: "omni.com",
    },
    {
      companyName: "Nova",
      description: "Fintech Solution",
      details: "Leading innovation",
      lastChecked: "July 22, 2026",
      performance: 91,
      status: "Failed",
      website: "nova.com",
    },
    {
      companyName: "Pioneer",
      description: "E-commerce Platform",
      details: "Revolutionizing the market",
      lastChecked: "July 20, 2026",
      performance: 84,
      status: "Failed",
      website: "pioneer.com",
    },
    {
      companyName: "Cosmos",
      description: "Cloud Service",
      details: "Cutting-edge technology",
      lastChecked: "July 6, 2026",
      performance: 91,
      status: "Paid",
      website: "cosmos.com",
    },
    {
      companyName: "Helix",
      description: "AI-powered Tool",
      details: "Next-gen solutions",
      lastChecked: "July 21, 2026",
      performance: 41,
      status: "Pending",
      website: "helix.com",
    },
    {
      companyName: "Zenith",
      description: "Blockchain App",
      details: "Advanced services",
      lastChecked: "July 14, 2026",
      performance: 15,
      status: "Failed",
      website: "zenith.com",
    },
    {
      companyName: "Quantum",
      description: "Healthcare Tech",
      details: "Premium experience",
      lastChecked: "July 14, 2026",
      performance: 83,
      status: "Failed",
      website: "quantum.com",
    },
    {
      companyName: "Apex",
      description: "EdTech Solution",
      details: "Top-notch performance",
      lastChecked: "July 10, 2026",
      performance: 21,
      status: "Paid",
      website: "apex.com",
    },
    {
      companyName: "Synergy",
      description: "Logistics App",
      details: "Unmatched quality",
      lastChecked: "July 18, 2026",
      performance: 46,
      status: "Paid",
      website: "synergy.com",
    },
    {
      companyName: "Vertex",
      description: "Gaming Platform",
      details: "Seamless integration",
      lastChecked: "July 3, 2026",
      performance: 32,
      status: "Failed",
      website: "vertex.com",
    },
    {
      companyName: "Omni",
      description: "Streaming Service",
      details: "Outstanding support",
      lastChecked: "July 2, 2026",
      performance: 58,
      status: "Failed",
      website: "omni.com",
    },
    {
      companyName: "Nova",
      description: "Fintech Solution",
      details: "Leading innovation",
      lastChecked: "July 3, 2026",
      performance: 8,
      status: "Failed",
      website: "nova.com",
    },
    {
      companyName: "Pioneer",
      description: "E-commerce Platform",
      details: "Revolutionizing the market",
      lastChecked: "July 23, 2026",
      performance: 95,
      status: "Failed",
      website: "pioneer.com",
    },
    {
      companyName: "Cosmos",
      description: "Cloud Service",
      details: "Cutting-edge technology",
      lastChecked: "July 4, 2026",
      performance: 86,
      status: "Pending",
      website: "cosmos.com",
    },
    {
      companyName: "Helix",
      description: "AI-powered Tool",
      details: "Next-gen solutions",
      lastChecked: "July 10, 2026",
      performance: 21,
      status: "Failed",
      website: "helix.com",
    },
    {
      companyName: "Zenith",
      description: "Blockchain App",
      details: "Advanced services",
      lastChecked: "July 8, 2026",
      performance: 42,
      status: "Pending",
      website: "zenith.com",
    },
    {
      companyName: "Quantum",
      description: "Healthcare Tech",
      details: "Premium experience",
      lastChecked: "July 8, 2026",
      performance: 67,
      status: "Paid",
      website: "quantum.com",
    },
    {
      companyName: "Apex",
      description: "EdTech Solution",
      details: "Top-notch performance",
      lastChecked: "July 9, 2026",
      performance: 18,
      status: "Paid",
      website: "apex.com",
    },
    {
      companyName: "Synergy",
      description: "Logistics App",
      details: "Unmatched quality",
      lastChecked: "July 17, 2026",
      performance: 56,
      status: "Paid",
      website: "synergy.com",
    },
    {
      companyName: "Vertex",
      description: "Gaming Platform",
      details: "Seamless integration",
      lastChecked: "July 13, 2026",
      performance: 80,
      status: "Pending",
      website: "vertex.com",
    },
    {
      companyName: "Omni",
      description: "Streaming Service",
      details: "Outstanding support",
      lastChecked: "July 21, 2026",
      performance: 19,
      status: "Paid",
      website: "omni.com",
    },
    {
      companyName: "Nova",
      description: "Fintech Solution",
      details: "Leading innovation",
      lastChecked: "July 10, 2026",
      performance: 54,
      status: "Pending",
      website: "nova.com",
    },
    {
      companyName: "Pioneer",
      description: "E-commerce Platform",
      details: "Revolutionizing the market",
      lastChecked: "July 5, 2026",
      performance: 37,
      status: "Pending",
      website: "pioneer.com",
    },
    {
      companyName: "Cosmos",
      description: "Cloud Service",
      details: "Cutting-edge technology",
      lastChecked: "July 24, 2026",
      performance: 58,
      status: "Pending",
      website: "cosmos.com",
    },
    {
      companyName: "Helix",
      description: "AI-powered Tool",
      details: "Next-gen solutions",
      lastChecked: "July 13, 2026",
      performance: 44,
      status: "Paid",
      website: "helix.com",
    },
    {
      companyName: "Zenith",
      description: "Blockchain App",
      details: "Advanced services",
      lastChecked: "July 8, 2026",
      performance: 41,
      status: "Failed",
      website: "zenith.com",
    },
    {
      companyName: "Quantum",
      description: "Healthcare Tech",
      details: "Premium experience",
      lastChecked: "July 6, 2026",
      performance: 74,
      status: "Pending",
      website: "quantum.com",
    },
    {
      companyName: "Apex",
      description: "EdTech Solution",
      details: "Top-notch performance",
      lastChecked: "July 3, 2026",
      performance: 83,
      status: "Failed",
      website: "apex.com",
    },
    {
      companyName: "Synergy",
      description: "Logistics App",
      details: "Unmatched quality",
      lastChecked: "July 8, 2026",
      performance: 90,
      status: "Pending",
      website: "synergy.com",
    },
    {
      companyName: "Vertex",
      description: "Gaming Platform",
      details: "Seamless integration",
      lastChecked: "July 14, 2026",
      performance: 67,
      status: "Paid",
      website: "vertex.com",
    },
    {
      companyName: "Omni",
      description: "Streaming Service",
      details: "Outstanding support",
      lastChecked: "July 25, 2026",
      performance: 27,
      status: "Paid",
      website: "omni.com",
    },
    {
      companyName: "Nova",
      description: "Fintech Solution",
      details: "Leading innovation",
      lastChecked: "July 10, 2026",
      performance: 24,
      status: "Pending",
      website: "nova.com",
    },
    {
      companyName: "Pioneer",
      description: "E-commerce Platform",
      details: "Revolutionizing the market",
      lastChecked: "July 11, 2026",
      performance: 91,
      status: "Paid",
      website: "pioneer.com",
    },
    {
      companyName: "Cosmos",
      description: "Cloud Service",
      details: "Cutting-edge technology",
      lastChecked: "July 13, 2026",
      performance: 85,
      status: "Paid",
      website: "cosmos.com",
    },
    {
      companyName: "Helix",
      description: "AI-powered Tool",
      details: "Next-gen solutions",
      lastChecked: "July 13, 2026",
      performance: 93,
      status: "Pending",
      website: "helix.com",
    },
    {
      companyName: "Zenith",
      description: "Blockchain App",
      details: "Advanced services",
      lastChecked: "July 3, 2026",
      performance: 23,
      status: "Pending",
      website: "zenith.com",
    },
    {
      companyName: "Quantum",
      description: "Healthcare Tech",
      details: "Premium experience",
      lastChecked: "July 2, 2026",
      performance: 17,
      status: "Paid",
      website: "quantum.com",
    },
    {
      companyName: "Apex",
      description: "EdTech Solution",
      details: "Top-notch performance",
      lastChecked: "July 8, 2026",
      performance: 5,
      status: "Failed",
      website: "apex.com",
    },
    {
      companyName: "Synergy",
      description: "Logistics App",
      details: "Unmatched quality",
      lastChecked: "July 15, 2026",
      performance: 58,
      status: "Pending",
      website: "synergy.com",
    },
    {
      companyName: "Vertex",
      description: "Gaming Platform",
      details: "Seamless integration",
      lastChecked: "July 7, 2026",
      performance: 50,
      status: "Pending",
      website: "vertex.com",
    },
    {
      companyName: "Omni",
      description: "Streaming Service",
      details: "Outstanding support",
      lastChecked: "July 13, 2026",
      performance: 33,
      status: "Pending",
      website: "omni.com",
    },
    {
      companyName: "Nova",
      description: "Fintech Solution",
      details: "Leading innovation",
      lastChecked: "July 27, 2026",
      performance: 86,
      status: "Paid",
      website: "nova.com",
    },
    {
      companyName: "Pioneer",
      description: "E-commerce Platform",
      details: "Revolutionizing the market",
      lastChecked: "July 9, 2026",
      performance: 9,
      status: "Pending",
      website: "pioneer.com",
    },
    {
      companyName: "Cosmos",
      description: "Cloud Service",
      details: "Cutting-edge technology",
      lastChecked: "July 19, 2026",
      performance: 69,
      status: "Failed",
      website: "cosmos.com",
    },
    {
      companyName: "Helix",
      description: "AI-powered Tool",
      details: "Next-gen solutions",
      lastChecked: "July 22, 2026",
      performance: 79,
      status: "Paid",
      website: "helix.com",
    },
    {
      companyName: "Zenith",
      description: "Blockchain App",
      details: "Advanced services",
      lastChecked: "July 7, 2026",
      performance: 71,
      status: "Pending",
      website: "zenith.com",
    },
    {
      companyName: "Quantum",
      description: "Healthcare Tech",
      details: "Premium experience",
      lastChecked: "July 11, 2026",
      performance: 77,
      status: "Paid",
      website: "quantum.com",
    },
    {
      companyName: "Apex",
      description: "EdTech Solution",
      details: "Top-notch performance",
      lastChecked: "July 15, 2026",
      performance: 29,
      status: "Pending",
      website: "apex.com",
    },
    {
      companyName: "Synergy",
      description: "Logistics App",
      details: "Unmatched quality",
      lastChecked: "July 11, 2026",
      performance: 71,
      status: "Pending",
      website: "synergy.com",
    },
    {
      companyName: "Vertex",
      description: "Gaming Platform",
      details: "Seamless integration",
      lastChecked: "July 15, 2026",
      performance: 24,
      status: "Pending",
      website: "vertex.com",
    },
    {
      companyName: "Omni",
      description: "Streaming Service",
      details: "Outstanding support",
      lastChecked: "July 12, 2026",
      performance: 6,
      status: "Failed",
      website: "omni.com",
    },
    {
      companyName: "Nova",
      description: "Fintech Solution",
      details: "Leading innovation",
      lastChecked: "July 14, 2026",
      performance: 89,
      status: "Paid",
      website: "nova.com",
    },
    {
      companyName: "Pioneer",
      description: "E-commerce Platform",
      details: "Revolutionizing the market",
      lastChecked: "July 1, 2026",
      performance: 62,
      status: "Failed",
      website: "pioneer.com",
    },
    {
      companyName: "Cosmos",
      description: "Cloud Service",
      details: "Cutting-edge technology",
      lastChecked: "July 6, 2026",
      performance: 81,
      status: "Paid",
      website: "cosmos.com",
    },
    {
      companyName: "Helix",
      description: "AI-powered Tool",
      details: "Next-gen solutions",
      lastChecked: "July 8, 2026",
      performance: 2,
      status: "Paid",
      website: "helix.com",
    },
    {
      companyName: "Zenith",
      description: "Blockchain App",
      details: "Advanced services",
      lastChecked: "July 10, 2026",
      performance: 40,
      status: "Paid",
      website: "zenith.com",
    },
    {
      companyName: "Quantum",
      description: "Healthcare Tech",
      details: "Premium experience",
      lastChecked: "July 16, 2026",
      performance: 48,
      status: "Failed",
      website: "quantum.com",
    },
    {
      companyName: "Apex",
      description: "EdTech Solution",
      details: "Top-notch performance",
      lastChecked: "July 13, 2026",
      performance: 6,
      status: "Pending",
      website: "apex.com",
    },
    {
      companyName: "Synergy",
      description: "Logistics App",
      details: "Unmatched quality",
      lastChecked: "July 5, 2026",
      performance: 61,
      status: "Pending",
      website: "synergy.com",
    },
    {
      companyName: "Vertex",
      description: "Gaming Platform",
      details: "Seamless integration",
      lastChecked: "July 16, 2026",
      performance: 16,
      status: "Pending",
      website: "vertex.com",
    },
    {
      companyName: "Omni",
      description: "Streaming Service",
      details: "Outstanding support",
      lastChecked: "July 20, 2026",
      performance: 8,
      status: "Failed",
      website: "omni.com",
    },
    {
      companyName: "Nova",
      description: "Fintech Solution",
      details: "Leading innovation",
      lastChecked: "July 12, 2026",
      performance: 11,
      status: "Failed",
      website: "nova.com",
    },
    {
      companyName: "Pioneer",
      description: "E-commerce Platform",
      details: "Revolutionizing the market",
      lastChecked: "July 8, 2026",
      performance: 40,
      status: "Pending",
      website: "pioneer.com",
    },
    {
      companyName: "Cosmos",
      description: "Cloud Service",
      details: "Cutting-edge technology",
      lastChecked: "July 28, 2026",
      performance: 60,
      status: "Paid",
      website: "cosmos.com",
    },
    {
      companyName: "Helix",
      description: "AI-powered Tool",
      details: "Next-gen solutions",
      lastChecked: "July 16, 2026",
      performance: 62,
      status: "Failed",
      website: "helix.com",
    },
    {
      companyName: "Zenith",
      description: "Blockchain App",
      details: "Advanced services",
      lastChecked: "July 25, 2026",
      performance: 64,
      status: "Failed",
      website: "zenith.com",
    },
    {
      companyName: "Quantum",
      description: "Healthcare Tech",
      details: "Premium experience",
      lastChecked: "July 27, 2026",
      performance: 50,
      status: "Pending",
      website: "quantum.com",
    },
    {
      companyName: "Apex",
      description: "EdTech Solution",
      details: "Top-notch performance",
      lastChecked: "July 8, 2026",
      performance: 66,
      status: "Paid",
      website: "apex.com",
    },
    {
      companyName: "Synergy",
      description: "Logistics App",
      details: "Unmatched quality",
      lastChecked: "July 18, 2026",
      performance: 8,
      status: "Failed",
      website: "synergy.com",
    },
    {
      companyName: "Vertex",
      description: "Gaming Platform",
      details: "Seamless integration",
      lastChecked: "July 3, 2026",
      performance: 18,
      status: "Failed",
      website: "vertex.com",
    },
    {
      companyName: "Omni",
      description: "Streaming Service",
      details: "Outstanding support",
      lastChecked: "July 15, 2026",
      performance: 10,
      status: "Paid",
      website: "omni.com",
    },
    {
      companyName: "Nova",
      description: "Fintech Solution",
      details: "Leading innovation",
      lastChecked: "July 4, 2026",
      performance: 60,
      status: "Failed",
      website: "nova.com",
    },
    {
      companyName: "Pioneer",
      description: "E-commerce Platform",
      details: "Revolutionizing the market",
      lastChecked: "July 4, 2026",
      performance: 68,
      status: "Paid",
      website: "pioneer.com",
    },
    {
      companyName: "Cosmos",
      description: "Cloud Service",
      details: "Cutting-edge technology",
      lastChecked: "July 12, 2026",
      performance: 83,
      status: "Pending",
      website: "cosmos.com",
    },
    {
      companyName: "Helix",
      description: "AI-powered Tool",
      details: "Next-gen solutions",
      lastChecked: "July 3, 2026",
      performance: 64,
      status: "Failed",
      website: "helix.com",
    },
    {
      companyName: "Zenith",
      description: "Blockchain App",
      details: "Advanced services",
      lastChecked: "July 3, 2026",
      performance: 19,
      status: "Failed",
      website: "zenith.com",
    },
    {
      companyName: "Quantum",
      description: "Healthcare Tech",
      details: "Premium experience",
      lastChecked: "July 23, 2026",
      performance: 65,
      status: "Failed",
      website: "quantum.com",
    },
    {
      companyName: "Apex",
      description: "EdTech Solution",
      details: "Top-notch performance",
      lastChecked: "July 17, 2026",
      performance: 81,
      status: "Failed",
      website: "apex.com",
    },
    {
      companyName: "Synergy",
      description: "Logistics App",
      details: "Unmatched quality",
      lastChecked: "July 22, 2026",
      performance: 1,
      status: "Pending",
      website: "synergy.com",
    },
    {
      companyName: "Vertex",
      description: "Gaming Platform",
      details: "Seamless integration",
      lastChecked: "July 4, 2026",
      performance: 47,
      status: "Failed",
      website: "vertex.com",
    },
    {
      companyName: "Omni",
      description: "Streaming Service",
      details: "Outstanding support",
      lastChecked: "July 14, 2026",
      performance: 47,
      status: "Paid",
      website: "omni.com",
    },
    {
      companyName: "Nova",
      description: "Fintech Solution",
      details: "Leading innovation",
      lastChecked: "July 24, 2026",
      performance: 66,
      status: "Pending",
      website: "nova.com",
    },
    {
      companyName: "Pioneer",
      description: "E-commerce Platform",
      details: "Revolutionizing the market",
      lastChecked: "July 7, 2026",
      performance: 47,
      status: "Failed",
      website: "pioneer.com",
    },
    {
      companyName: "Cosmos",
      description: "Cloud Service",
      details: "Cutting-edge technology",
      lastChecked: "July 27, 2026",
      performance: 61,
      status: "Paid",
      website: "cosmos.com",
    },
    {
      companyName: "Helix",
      description: "AI-powered Tool",
      details: "Next-gen solutions",
      lastChecked: "July 10, 2026",
      performance: 56,
      status: "Pending",
      website: "helix.com",
    },
    {
      companyName: "Zenith",
      description: "Blockchain App",
      details: "Advanced services",
      lastChecked: "July 1, 2026",
      performance: 98,
      status: "Failed",
      website: "zenith.com",
    },
    {
      companyName: "Quantum",
      description: "Healthcare Tech",
      details: "Premium experience",
      lastChecked: "July 21, 2026",
      performance: 17,
      status: "Failed",
      website: "quantum.com",
    },
    {
      companyName: "Apex",
      description: "EdTech Solution",
      details: "Top-notch performance",
      lastChecked: "July 17, 2026",
      performance: 26,
      status: "Pending",
      website: "apex.com",
    },
    {
      companyName: "Synergy",
      description: "Logistics App",
      details: "Unmatched quality",
      lastChecked: "July 11, 2026",
      performance: 46,
      status: "Paid",
      website: "synergy.com",
    },
    {
      companyName: "Vertex",
      description: "Gaming Platform",
      details: "Seamless integration",
      lastChecked: "July 12, 2026",
      performance: 16,
      status: "Pending",
      website: "vertex.com",
    },
    {
      companyName: "Omni",
      description: "Streaming Service",
      details: "Outstanding support",
      lastChecked: "July 15, 2026",
      performance: 1,
      status: "Pending",
      website: "omni.com",
    },
    {
      companyName: "Nova",
      description: "Fintech Solution",
      details: "Leading innovation",
      lastChecked: "July 4, 2026",
      performance: 59,
      status: "Paid",
      website: "nova.com",
    },
    {
      companyName: "Pioneer",
      description: "E-commerce Platform",
      details: "Revolutionizing the market",
      lastChecked: "July 7, 2026",
      performance: 88,
      status: "Pending",
      website: "pioneer.com",
    },
    {
      companyName: "Cosmos",
      description: "Cloud Service",
      details: "Cutting-edge technology",
      lastChecked: "July 3, 2026",
      performance: 32,
      status: "Paid",
      website: "cosmos.com",
    },
    {
      companyName: "Helix",
      description: "AI-powered Tool",
      details: "Next-gen solutions",
      lastChecked: "July 9, 2026",
      performance: 48,
      status: "Failed",
      website: "helix.com",
    },
    {
      companyName: "Zenith",
      description: "Blockchain App",
      details: "Advanced services",
      lastChecked: "July 8, 2026",
      performance: 65,
      status: "Failed",
      website: "zenith.com",
    },
    {
      companyName: "Quantum",
      description: "Healthcare Tech",
      details: "Premium experience",
      lastChecked: "July 25, 2026",
      performance: 13,
      status: "Paid",
      website: "quantum.com",
    },
    {
      companyName: "Apex",
      description: "EdTech Solution",
      details: "Top-notch performance",
      lastChecked: "July 26, 2026",
      performance: 10,
      status: "Paid",
      website: "apex.com",
    },
    {
      companyName: "Synergy",
      description: "Logistics App",
      details: "Unmatched quality",
      lastChecked: "July 20, 2026",
      performance: 5,
      status: "Pending",
      website: "synergy.com",
    },
    {
      companyName: "Vertex",
      description: "Gaming Platform",
      details: "Seamless integration",
      lastChecked: "July 19, 2026",
      performance: 23,
      status: "Pending",
      website: "vertex.com",
    },
    {
      companyName: "Omni",
      description: "Streaming Service",
      details: "Outstanding support",
      lastChecked: "July 3, 2026",
      performance: 24,
      status: "Pending",
      website: "omni.com",
    },
    {
      companyName: "Nova",
      description: "Fintech Solution",
      details: "Leading innovation",
      lastChecked: "July 22, 2026",
      performance: 79,
      status: "Pending",
      website: "nova.com",
    },
    {
      companyName: "Pioneer",
      description: "E-commerce Platform",
      details: "Revolutionizing the market",
      lastChecked: "July 2, 2026",
      performance: 4,
      status: "Paid",
      website: "pioneer.com",
    },
    {
      companyName: "Cosmos",
      description: "Cloud Service",
      details: "Cutting-edge technology",
      lastChecked: "July 4, 2026",
      performance: 97,
      status: "Failed",
      website: "cosmos.com",
    },
    {
      companyName: "Helix",
      description: "AI-powered Tool",
      details: "Next-gen solutions",
      lastChecked: "July 8, 2026",
      performance: 55,
      status: "Failed",
      website: "helix.com",
    },
    {
      companyName: "Zenith",
      description: "Blockchain App",
      details: "Advanced services",
      lastChecked: "July 28, 2026",
      performance: 78,
      status: "Failed",
      website: "zenith.com",
    },
    {
      companyName: "Quantum",
      description: "Healthcare Tech",
      details: "Premium experience",
      lastChecked: "July 5, 2026",
      performance: 28,
      status: "Pending",
      website: "quantum.com",
    },
    {
      companyName: "Apex",
      description: "EdTech Solution",
      details: "Top-notch performance",
      lastChecked: "July 17, 2026",
      performance: 46,
      status: "Failed",
      website: "apex.com",
    },
    {
      companyName: "Synergy",
      description: "Logistics App",
      details: "Unmatched quality",
      lastChecked: "July 19, 2026",
      performance: 47,
      status: "Failed",
      website: "synergy.com",
    },
    {
      companyName: "Vertex",
      description: "Gaming Platform",
      details: "Seamless integration",
      lastChecked: "July 11, 2026",
      performance: 87,
      status: "Failed",
      website: "vertex.com",
    },
    {
      companyName: "Omni",
      description: "Streaming Service",
      details: "Outstanding support",
      lastChecked: "July 19, 2026",
      performance: 94,
      status: "Failed",
      website: "omni.com",
    },
    {
      companyName: "Nova",
      description: "Fintech Solution",
      details: "Leading innovation",
      lastChecked: "July 7, 2026",
      performance: 84,
      status: "Pending",
      website: "nova.com",
    },
    {
      companyName: "Pioneer",
      description: "E-commerce Platform",
      details: "Revolutionizing the market",
      lastChecked: "July 25, 2026",
      performance: 3,
      status: "Failed",
      website: "pioneer.com",
    },
    {
      companyName: "Cosmos",
      description: "Cloud Service",
      details: "Cutting-edge technology",
      lastChecked: "July 23, 2026",
      performance: 80,
      status: "Failed",
      website: "cosmos.com",
    },
    {
      companyName: "Helix",
      description: "AI-powered Tool",
      details: "Next-gen solutions",
      lastChecked: "July 22, 2026",
      performance: 38,
      status: "Paid",
      website: "helix.com",
    },
    {
      companyName: "Zenith",
      description: "Blockchain App",
      details: "Advanced services",
      lastChecked: "July 6, 2026",
      performance: 92,
      status: "Failed",
      website: "zenith.com",
    },
    {
      companyName: "Quantum",
      description: "Healthcare Tech",
      details: "Premium experience",
      lastChecked: "July 24, 2026",
      performance: 86,
      status: "Paid",
      website: "quantum.com",
    },
    {
      companyName: "Apex",
      description: "EdTech Solution",
      details: "Top-notch performance",
      lastChecked: "July 10, 2026",
      performance: 24,
      status: "Pending",
      website: "apex.com",
    },
    {
      companyName: "Synergy",
      description: "Logistics App",
      details: "Unmatched quality",
      lastChecked: "July 23, 2026",
      performance: 58,
      status: "Paid",
      website: "synergy.com",
    },
    {
      companyName: "Vertex",
      description: "Gaming Platform",
      details: "Seamless integration",
      lastChecked: "July 26, 2026",
      performance: 20,
      status: "Failed",
      website: "vertex.com",
    },
    {
      companyName: "Omni",
      description: "Streaming Service",
      details: "Outstanding support",
      lastChecked: "July 9, 2026",
      performance: 86,
      status: "Paid",
      website: "omni.com",
    },
    {
      companyName: "Nova",
      description: "Fintech Solution",
      details: "Leading innovation",
      lastChecked: "July 27, 2026",
      performance: 25,
      status: "Failed",
      website: "nova.com",
    },
    {
      companyName: "Pioneer",
      description: "E-commerce Platform",
      details: "Revolutionizing the market",
      lastChecked: "July 8, 2026",
      performance: 2,
      status: "Failed",
      website: "pioneer.com",
    },
    {
      companyName: "Cosmos",
      description: "Cloud Service",
      details: "Cutting-edge technology",
      lastChecked: "July 17, 2026",
      performance: 12,
      status: "Paid",
      website: "cosmos.com",
    },
    {
      companyName: "Helix",
      description: "AI-powered Tool",
      details: "Next-gen solutions",
      lastChecked: "July 12, 2026",
      performance: 1,
      status: "Pending",
      website: "helix.com",
    },
    {
      companyName: "Zenith",
      description: "Blockchain App",
      details: "Advanced services",
      lastChecked: "July 12, 2026",
      performance: 45,
      status: "Paid",
      website: "zenith.com",
    },
    {
      companyName: "Quantum",
      description: "Healthcare Tech",
      details: "Premium experience",
      lastChecked: "July 26, 2026",
      performance: 94,
      status: "Paid",
      website: "quantum.com",
    },
    {
      companyName: "Apex",
      description: "EdTech Solution",
      details: "Top-notch performance",
      lastChecked: "July 1, 2026",
      performance: 13,
      status: "Failed",
      website: "apex.com",
    },
    {
      companyName: "Synergy",
      description: "Logistics App",
      details: "Unmatched quality",
      lastChecked: "July 8, 2026",
      performance: 71,
      status: "Failed",
      website: "synergy.com",
    },
    {
      companyName: "Vertex",
      description: "Gaming Platform",
      details: "Seamless integration",
      lastChecked: "July 20, 2026",
      performance: 63,
      status: "Failed",
      website: "vertex.com",
    },
    {
      companyName: "Omni",
      description: "Streaming Service",
      details: "Outstanding support",
      lastChecked: "July 16, 2026",
      performance: 1,
      status: "Paid",
      website: "omni.com",
    },
  ],
};
